### ISSUE TITLE
Better documentation?

### ISSUE THREAD

**Issue by thepenguinthatwants** [Bluewind/App-BorgRestore#1]
Hiya!

This looks promising yet I have no clue how to get it running.

`The example is borg-restore.pl bin/backup.sh `

So does it need to run throught certain bash script? I tried to use it on my borg repo like this

`borg-restore.pl Backup`

As the Backup is my borg repo.

The error I get is 
[Connection closed by remote host. Is borg working on the server?
ERROR borg list returned 512
FATAL Uncaught exception: borg list returned 512](url)

**Comment by Bluewind** [comment]
`bin/backup.sh` in this case is just the path of a file that you want to restore. I can see how the example I've chosen may be confusing. The issue you have sounds like `borg list` which is  called by borg-restore.pl does not manage to connect via SSH. Do you use SSH keys or an SSH client config that may not be used when borg is run by borg-restore.pl? Maybe your SSH agent is not available? I believe sudo clears some environment variables and can thus prevent the SSH agent from being used.

**Comment by thepenguinthatwants** [comment]
I am actually trying to run this locally on my own Arch Linux server. So I guess there should be no interference with SSH.

I created a file in my home directory  borg-restore.cfg 
and it now consists 
`$borg_repo = "/home/john/Backup";`

When I run

`borg-restore.pl --update-cache`

I still get the same error. Unsure if I understood it wrongly as I thought running 

`borg-restore.pl <repo>`
I should get a prompt to choose which backup to choose from.

**Comment by Bluewind** [comment]
What's the full path of your config file? It should be in `$XDG_CONFIG_HOME` (or `$HOME/.config/`), not in your home directory directly.

Regarding your second point: Yes, you first need to run `borg-restore.pl --update-cache` and when that completes (successfully) you can run `borg-restore.pl <path>`. However, note that here the argument is a path to file or directory that you want to restore. It is not a repo.

**Comment by thepenguinthatwants** [comment]
Hi!
Oh now I understand so the idea. Thanks it works now... this tool is quite powerful.

I guess I would've understand more of it if I've checked more about the script. Thanks for the help! Much appreciated!
