### ISSUE TITLE
Underscores in archive names?

### ISSUE THREAD

**Issue by szoemi** [Bluewind/App-BorgRestore#4]
I did a borg-restore.pl --update-cache the first time ever. It has processed the long list of archives, then it crashed. The crash happened at the first archive that had underscores (_) in its name. After renaming the archive by replacing the underscore with dashes (-), it did not crash at that archive, but it did again with the next archive with underscores in its name. Then I renamed all archives, replacing underscores with dashes. There were no crashes afterwards.

Platform: Slackware 14.2

perl 5, version 22, subversion 2 (v5.22.2) built for x86_64-linux-thread-multi

borg-restore.pl  --version:
Version: 3.3.0

Error:
INFO Adding archive spf_KXZ_190803
FATAL Uncaught exception: Failed to untaint: spf_KXZ_190803 at /usr/local/share/perl5/App/BorgRestore/Helper.pm line 22.

Error:

**Comment by Bluewind** [comment]
Fixed in 3.4.0
